# for the performance of 2022 free agent signings from year 2021
CREATE TABLE perf2022 AS
SELECT m.Name,
       m.date, 
       m.new_team,
       m.former_team,
       m.Age,
       m.WAR3,
       m.Yrs,
       m.career_games,
       m.stayed_same_team,
       t.G,
       t.PA,
       t.HR,
       t.R,
       t.RBI,
       t.SB,
       t.`BB%`,
       t.`K%`,
       t.AVG,
       t.OBP,
       t.SLG,
       t.GDP,
       t.CS,
       t.H,
       t.OPS,
       t.PlayerId,
       t.MLBAMID
FROM salaries2022 m
LEFT JOIN trad_stats2021 t ON m.Name = t.NameASCII;

#for perf2022_2, im adding the 2019 stats 

CREATE TABLE perf2022_2 AS
SELECT m.Name,
       m.date,
       m.new_team,
       m.former_team,
       m.Age,
       m.WAR3,
       m.Yrs,
       m.career_games,
       m.stayed_same_team,
       m.G,
       m.PA,
       m.HR,
       m.R,
       m.RBI,
       m.SB,
       m.`BB%`,
       m.`K%`,
       m.AVG,
       m.OBP,
       m.SLG,
       m.GDP,
       m.CS,
       m.H,
       m.OPS,
       m.PlayerId,
       m.MLBAMID,
       t.G AS G_2,
       t.PA AS PA_2,
       t.HR AS HR_2,
       t.R AS R_2,
       t.RBI AS RBI_2,
       t.SB AS SB_2,
       t.`BB%` AS `BB%_2`,
       t.`K%` AS `K%_2`,
       t.AVG AS AVG_2,
       t.OBP AS OBP_2,
       t.SLG AS SLG_2,
       t.GDP AS GDP_2,
       t.CS AS CS_2,
       t.H AS H_2,
       t.OPS AS OPS_2
FROM perf2022 m
LEFT JOIN trad_stats2019 t ON m.PlayerId = t.PlayerId;

#join trad_stats2018 to perf2022_2. 2018 column names end in '_3'
CREATE TABLE perf2022_3 AS
SELECT m.Name,
       m.date,
       m.new_team,
       m.former_team,
       m.Age,
       m.WAR3,
       m.Yrs,
       m.career_games,
       m.stayed_same_team,
       m.G,
       m.PA,
       m.HR,
       m.R,
       m.RBI,
       m.SB,
       m.`BB%`,
       m.`K%`,
       m.AVG,
       m.OBP,
       m.SLG,
       m.GDP,
       m.CS,
       m.H,
       m.OPS,
       m.PlayerId,
       m.MLBAMID,
       m.G_2,
       m.PA_2,
       m.HR_2,
       m.R_2,
       m.RBI_2,
       m.SB_2,
       m.`BB%_2`,
       m.`K%_2`,
       m.AVG_2,
       m.OBP_2,
       m.SLG_2,
       m.GDP_2,
       m.CS_2,
       m.H_2,
       m.OPS_2,
       t_3.G AS G_3,
       t_3.PA AS PA_3,
       t_3.HR AS HR_3,
       t_3.R AS R_3,
       t_3.RBI AS RBI_3,
       t_3.SB AS SB_3,
       t_3.`BB%` AS `BB%_3`,
       t_3.`K%` AS `K%_3`,
       t_3.AVG AS AVG_3,
       t_3.OBP AS OBP_3,
       t_3.SLG AS SLG_3,
       t_3.GDP AS GDP_3,
       t_3.CS AS CS_3,
       t_3.H AS H_3,
       t_3.OPS AS OPS_3
FROM perf2022_2 m
LEFT JOIN trad_stats2018 t_3 ON m.PlayerId = t_3.PlayerId; ### change this